export const validation = {
  emptyEmailField: "Please Enter Email.",
  invalidEmail: "Email is Invalid.",
  emptyPasswordField: "Please Enter Password.",
  emptyConfirmPasswordField: "Please Enter Confirm Password.",
  invalidPassword:
    "Password must contain Digit, Lower case, Upper case, special Characters and min 8 char max 32 char.",
  confirmPasswordNotMatched: "Confirm Password does not match Password.",
  acceptServiceAgreement: "Please Accept Agreement",
  referralCodeRequired: "Please Enter Referral Code",
  emptyNewPasswordField: "Please Enter New Password",
  emptyNewConfirmPasswordField: "Please Enter Confirm New Password",
  confirmNewPasswordNotMatched:
    "Confirm New Password does not match New Password.",
  firstNameEmpty: "Please Enter First Name.",
  lastNameEmpty: "Please Enter Last Name.",
  phoneNumberRequired: "Please Enter Phone Number.",
  DOBRequired: "Please Enter Date Of Birth.",
  invalidPhoneNumber: "Phone Number is Invalid.",
  invalidCPFCNPJ: "CPF / CNPJ# is invalid.",
  currentPasswordRequired: "Please Enter Current Password.",
  newPasswordRequired: "Please Enter New Password.",
  retypeNewPasswordRequired: "Please Enter Retype New Password.",
  matchNewPassword: "Retype New Password does not match New Password",
  captchaRequired: "Please Enter Captcha.",
  requiredtermsCondition: "Please Select Terms & Conditions.",
  noRecordFound: "No Record Found.",
  selectDateAndTime: "Please Select Date & Time.",
};
